edition = "2021"
max_width = 80
match_block_trailing_comma = true
imports_granularity = "Crate"
reorder_impl_items = true
struct_field_align_threshold = 20
tab_spaces = 2
use_field_init_shorthand = true
use_try_shorthand = true
